version: "3.8"
services:
  apate:
    container_name: apate
    ports:
      - "10001:10001"
    image: adoptopenjdk/maven-openjdk8
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "mvn clean package -DskipTests && java -jar target/*.jar"
    environment:
      - TZ=Asia/Shanghai