name: deploy apate to niostack.com
run-name: ${{ github.actor }} is deploying to server 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:        

      - name: Deploy by ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: niostack.com
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: cd /root/apate && git add . && git reset --hard && git pull && docker-compose stop && docker-compose up --build -d && docker-compose logs --tail=3